# Generated by Django 5.0 on 2024-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/category')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, default='+091', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='images/default_pro.png', null=True, upload_to='images/user_profile'),
        ),
    ]
