# Generated by Django 5.0 on 2024-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
